name: Build and Release eclipse.jdt.ls

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      release-notes:
        description: 'Release notes'
        required: false
        default: 'Automated build of eclipse.jdt.ls'

env:
  BUILD_DIR: eclipse.jdt.ls

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build eclipse.jdt.ls
      run: |
        # Navigate to the submodule directory
        cd $BUILD_DIR
        
        # Make mvnw executable
        chmod +x ./mvnw
        
        # Build with Java 21, skip tests, and update snapshots
        JAVA_HOME=$JAVA_HOME ./mvnw clean verify -U -DskipTests=true

    - name: Create build artifacts archive
      run: |
        cd $BUILD_DIR/org.eclipse.jdt.ls.product/target/repository/
        tar -czf ../eclipse-jdt-ls-build.tar.gz .
        cd ..
        zip -r eclipse-jdt-ls-build.zip repository/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: eclipse-jdt-ls-build
        path: |
          ${{ env.BUILD_DIR }}/org.eclipse.jdt.ls.product/target/eclipse-jdt-ls-build.tar.gz
          ${{ env.BUILD_DIR }}/org.eclipse.jdt.ls.product/target/eclipse-jdt-ls-build.zip
        retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: eclipse-jdt-ls-build
        path: ./artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.release-tag }}
        name: ${{ github.event.inputs.release-tag }}
        body: ${{ github.event.inputs.release-notes }}
        files: |
          ./artifacts/eclipse-jdt-ls-build.tar.gz
          ./artifacts/eclipse-jdt-ls-build.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release artifacts to GitHub
      run: |
        echo "Release created successfully with artifacts:"
        ls -la ./artifacts/
